// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl-gDFLvfBGgSdrsgfsd3jjx3WYzoRp_8',
    appId: '1:308988723183:web:ad18da269a57f12523801a',
    messagingSenderId: '308988723183',
    projectId: 'email-service-app-61c1b',
    authDomain: 'email-service-app-61c1b.firebaseapp.com',
    storageBucket: 'email-service-app-61c1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCxl69nQa74p5u4F9OWSH3V26T_3UCgE',
    appId: '1:308988723183:android:866fed9ac744a71123801a',
    messagingSenderId: '308988723183',
    projectId: 'email-service-app-61c1b',
    storageBucket: 'email-service-app-61c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCaOGTIGKz2t_6TRparGCn3yBqwzQx8hg',
    appId: '1:308988723183:ios:a53272aa8ef7f0a823801a',
    messagingSenderId: '308988723183',
    projectId: 'email-service-app-61c1b',
    storageBucket: 'email-service-app-61c1b.firebasestorage.app',
    iosBundleId: 'com.example.simulatedEmailServiceApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCaOGTIGKz2t_6TRparGCn3yBqwzQx8hg',
    appId: '1:308988723183:ios:a53272aa8ef7f0a823801a',
    messagingSenderId: '308988723183',
    projectId: 'email-service-app-61c1b',
    storageBucket: 'email-service-app-61c1b.firebasestorage.app',
    iosBundleId: 'com.example.simulatedEmailServiceApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl-gDFLvfBGgSdrsgfsd3jjx3WYzoRp_8',
    appId: '1:308988723183:web:78d0faa7f176835623801a',
    messagingSenderId: '308988723183',
    projectId: 'email-service-app-61c1b',
    authDomain: 'email-service-app-61c1b.firebaseapp.com',
    storageBucket: 'email-service-app-61c1b.firebasestorage.app',
  );
}
